Please use Markdown cells in your submission to document your thought process. You are expected to follow the clean code and PEP 8 guidelines as much as you can. You should use docstrings for all function declarations.
In this assignment, you will learn several functions from numpy. Please check their functionalities using their documentations or help() function, and see if you can apply them to solve the homework problems.

# Cosin Similarity
Cosine similarity measures the similarity between two high dimensional vectors. It is widely-used in applications such as clustering tasks in machine learning, building recommendation systems for e-commerce companies. See more background on cosine similarity in [Wikipedia](https://en.wikipedia.org/wiki/Cosine_similarity). 

Write a function named "cosine_similarity". The function takes two 1D numpy arrays as inputs, and returns their cosine similarity. 

**Note**: You are allowed to use np.dot() for inner product, np.sum() for summation, np.sqrt() for calculating square root. Do not use other built-in functions from Numpy such as np.linalg.norm(). 


### The formula is:

\[
\text{cosine\_similarity}(A, B) = \frac{A \cdot B}{\|A\| \times \|B\|}
\]
### Step 1: Compute the dot product  
Use `np.dot(a, b)` to calculate \( A \cdot B \).


In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)
dot_product


np.int64(32)

### Step 2: Compute the magnitude of each vector  
We use `np.sum()` to get the sum of squares, then `np.sqrt()` for the square root.


In [2]:
magnitude_a = np.sqrt(np.sum(a ** 2))
magnitude_b = np.sqrt(np.sum(b ** 2))
magnitude_a, magnitude_b


(np.float64(3.7416573867739413), np.float64(8.774964387392123))

### Step 3: Calculate cosine similarity  
Divide the dot product by the product of magnitudes.


In [3]:
cosine_similarity_value = dot_product / (magnitude_a * magnitude_b)
cosine_similarity_value


np.float64(0.9746318461970762)

### Step 4: Define the function  
Define a function `cosine_similarity(a, b)` that performs all the steps above.


In [7]:
def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
    """
    Calculate the cosine similarity between two 1D numpy arrays.

    Parameters :

    a : np.ndarray
        First input vector.
    b : np.ndarray
        Second input vector.

    Returns :

    float
        Cosine similarity value between a and b.
    """
    dot_product = np.dot(a, b)
    magnitude_a = np.sqrt(np.sum(a ** 2))
    magnitude_b = np.sqrt(np.sum(b ** 2))
    cosine_sim = dot_product / (magnitude_a * magnitude_b)
    return cosine_sim


### Step 5: Test the function
Run the function with example arrays.


In [6]:
result = cosine_similarity(np.array([1, 2, 3]), np.array([4, 5, 6]))
print("Cosine Similarity:", result)


Cosine Similarity: 0.9746318461970762


# Stock Price Analysis--Part I
Write a function named "count_max_streak". The function takes the historical stock price data, represented as a 1D numpy array, as input, and returns the maximum number of consecutive days when the stock price increased. 

To test your function, please use `tesla_closing_price` as the 1D numpy array input to your function. The historical stock price of Tesla is provided for you to test your code.

```py
import pandas as pd
tesla = pd.read_csv('TSLA.csv') # load Tesla stock price from csv file
tesla_np = tesla.to_numpy() # convert the data to numpy arrays
tesla_closing_price = tesla_np[:, 4] # extract the closing stock price of Tesla
```

### Step 1: Load the Tesla stock data  
Read the CSV file and extract the closing prices (column index 4).


In [14]:
import numpy as np
import pandas as pd

path = r"C:\Users\HP\Desktop\509_demo\assignment-5-numpy-Sienna-Zhang\TSLA.csv"

tesla = pd.read_csv(path)          # Load Tesla stock price data
tesla_np = tesla.to_numpy()              # Convert to NumPy array
tesla_closing_price = tesla_np[:, 4]     # Extract closing prices


### Step 2: Problem explanation  
Compare each day's price with the previous day's price.  
If today's price > yesterday's price, then it’s an “increase day.”  
Count the longest continuous run of such increases.


In [16]:
# Example of comparison logic
price_changes = tesla_closing_price[1:] > tesla_closing_price[:-1]
price_changes[:10]  # True means the price went up compared to the previous day


array([False, False, False, False, False,  True, False, False,  True,
        True])

### Step 3: Define the function `count_max_streak`

1. Create a Boolean array of price increases.
2. Loop through it to count consecutive `True` values.
3. Keep track of the maximum streak length.


In [17]:
def count_max_streak(prices: np.ndarray) -> int:
    """
    Count the maximum number of consecutive days
    when the stock price increased.

    Parameters :

    prices : np.ndarray
        1D array of daily closing stock prices.

    Returns :

    int
        The maximum streak (number of consecutive increases).
    """
    # Boolean array: True if today's price > yesterday's
    increase = prices[1:] > prices[:-1]
    
    max_streak = 0
    current_streak = 0
    
    for inc in increase:
        if inc:
            current_streak += 1
            max_streak = max(max_streak, current_streak)
        else:
            current_streak = 0
    
    return max_streak


### Step 4: Test the function with Tesla’s closing prices


In [18]:
max_increase_streak = count_max_streak(tesla_closing_price)
print("Maximum consecutive increase days:", max_increase_streak)


Maximum consecutive increase days: 8


# Stock Price Analysis--Part 2
Write a function named "detect_crash". The function takes a 2D numpy array as input, where the first column represents the historical opening stock price, and the second column represents the historical closing stock price. The function should return a 2D numpy array whose first column contains the indices when crashes occurred, and whose second column contains amount of price drop. 

**Note**: We say there is a stock price crash if the closing price is less than the opening price.

**Hint**: You may find functions np.where() and np.column_stack() helpful. You are also welcome to come up with other solutions without using these functions. 

To test your function, please use `open_close_prices` as the 2D numpy array input to your function. You can download the historical stock price of Tesla here.

```py
import pandas as pd
tesla = pd.read_csv('TSLA.csv') # load Tesla stock price from csv file
tesla_np = tesla.to_numpy() # convert the data to numpy arrays
tesla_opening_price = tesla_np[:, 1] # extract the closing stock price of Tesla
tesla_closing_price = tesla_np[:, 4] # extract the closing stock price of Tesla
open_close_price = np.column_stack((tesla_opening_price, tesla_closing_price)) # form a 2D numpy array using opening and closing prices 
```

### Step 1: Load Tesla stock price data


In [19]:
import numpy as np
import pandas as pd

path = r"C:\Users\HP\Desktop\509_demo\assignment-5-numpy-Sienna-Zhang\TSLA.csv"

tesla = pd.read_csv(path)
tesla_np = tesla.to_numpy()

# Extract opening and closing prices
tesla_opening_price = tesla_np[:, 1]   # column 1 = Open
tesla_closing_price = tesla_np[:, 4]   # column 4 = Close

# Combine them into a 2D array
open_close_price = np.column_stack((tesla_opening_price, tesla_closing_price))
open_close_price[:5]  # show first 5 rows


array([[19.0, 23.889999],
       [25.790001, 23.83],
       [25.0, 21.959999],
       [23.0, 19.200001],
       [20.0, 16.110001]], dtype=object)

### Step 2: Problem explanation
A “crash” happens when the **closing price < opening price**.  
Find such indices using `np.where()` and compute the drop amount.


In [20]:
crash_indices = np.where(open_close_price[:, 1] < open_close_price[:, 0])[0]
crash_amounts = open_close_price[crash_indices, 0] - open_close_price[crash_indices, 1]
np.column_stack((crash_indices, crash_amounts))[:5]


array([[1, 1.9600010000000019],
       [2, 3.040001],
       [3, 3.7999989999999997],
       [4, 3.8899989999999995],
       [5, 0.5999999999999979]], dtype=object)

### Step 3: Define the function `detect_crash`


In [ ]:
def detect_crash(open_close_prices: np.ndarray) -> np.ndarray:
    """
    Detect stock price crashes.

    Parameters :

    open_close_prices : np.ndarray
        2D array where:
        - Column 0: Opening prices
        - Column 1: Closing prices

    Returns :

    np.ndarray
        2D array where:
        - Column 0: indices of crash days
        - Column 1: amount of price drop
    """
    # Find crash indices
    crash_indices = np.where(open_close_prices[:, 1] < open_close_prices[:, 0])[0]

    # Compute drop amount
    crash_amounts = open_close_prices[crash_indices, 0] - open_close_prices[crash_indices, 1]

    # Combine results into one 2D array
    crashes = np.column_stack((crash_indices, crash_amounts))

    return crashes


### Step 4: Test the function with Tesla data


In [22]:
crash_result = detect_crash(open_close_price)
print("First 10 crash records:\n", crash_result[:10])
print("\nTotal number of crashes:", len(crash_result))


First 10 crash records:
 [[1 1.9600010000000019]
 [2 3.040001]
 [3 3.7999989999999997]
 [4 3.8899989999999995]
 [5 0.5999999999999979]
 [7 0.17999999999999972]
 [8 0.9000020000000006]
 [11 0.050001999999999214]
 [12 0.06000200000000078]
 [14 1.5500010000000017]]

Total number of crashes: 1129


# Infectious Disease Simulation

Write a function named "simulate_disease" to simulate how infectious disease may propagate over a network. Given the infection probabilities  of all individuals at time  and a network connection , the infection probabilities at time step  is computed as . Here are the requirements of this function:

The function uses a 1D numpy array to denote the probabilities of all individuals within the network of being infected. 
The network connection among individuals is represented using a 2D symmetric, row-stochastic numpy array, with all entries being non-negative (A row-stochastic matrix is one whose elements adds up to 1 for each row). If there are N individuals in the network, the matrix is of dimension . The -th entry of the matrix represents the connection strength between individual  and . 
Given the initial probability, the network connections, and prediction time horizon, the function returns the probabilities of each individual in the network of getting disease at the end of prediction time horizon.
You can use the following code snippet to generate a random connection matrix of dimension  to verify your function:
```py
np.random.seed(20)
matrix = np.random.rand(N, N)
symmetric_matrix = (matrix + matrix.T) / 2
connection_matrix = symmetric_matrix / symmetric_matrix.sum(axis=1, keepdims=True)
```
You can use the following code snippet to generate an initial infection probability: `np.random.rand(N, 1)`

### Step 1 — Generate example data
Create a **symmetric, row-stochastic** matrix `W` to represent network connections  
and an initial infection probability vector `p0`.


In [23]:
import numpy as np

N = 6
np.random.seed(20)

matrix = np.random.rand(N, N)
symmetric_matrix = (matrix + matrix.T) / 2
W = symmetric_matrix / symmetric_matrix.sum(axis=1, keepdims=True)

p0 = np.random.rand(N, 1)  # initial infection probabilities
p0[:5], W.shape


(array([[0.32920641],
        [0.51064106],
        [0.26362883],
        [0.31051155],
        [0.62685344]]),
 (6, 6))

### Step 2 — Check matrix properties (optional)
Verify non-negativity, row sums ≈ 1, and symmetry.


In [24]:
print("Non-negative:", np.all(W >= 0))
print("Row sums (first 5):", W.sum(axis=1)[:5])
print("Symmetric (allclose):", np.allclose(W, W.T))


Non-negative: True
Row sums (first 5): [1. 1. 1. 1. 1.]
Symmetric (allclose): False


### Step 3 — Single-step propagation
Compute \( p_{t+1} = W p_t \).


In [25]:
p1 = W @ p0
p1[:5]


array([[0.41819982],
       [0.4261734 ],
       [0.41178342],
       [0.40666418],
       [0.43538739]])

### Step 4 — Multi-step propagation (manual loop demo)
Run several updates to see how probabilities evolve.


In [26]:
steps = 3
p = p0.reshape(-1)  # convert to 1-D
for _ in range(steps):
    p = W @ p
    p = np.clip(p, 0.0, 1.0)  # keep values in [0, 1]
p[:5]


array([0.42475655, 0.42518765, 0.42482453, 0.42351832, 0.42442553])

### Step 5 — Define the reusable function `simulate_disease`


In [27]:
def simulate_disease(p0: np.ndarray, connection_matrix: np.ndarray, steps: int) -> np.ndarray:
    """
    Simulate disease propagation over a network using p_{t+1} = W p_t.

    Parameters :

    p0 : np.ndarray
        Initial infection probabilities, shape (N,) or (N, 1).
    connection_matrix : np.ndarray
        Symmetric, row-stochastic, non-negative matrix W of shape (N, N).
    steps : int
        Number of update steps (prediction horizon), must be >= 0.

    Returns :

    np.ndarray
        Final infection probabilities as a 1-D array of shape (N,).
    """
    # Convert inputs to proper numeric arrays
    p = np.asarray(p0, dtype=float).reshape(-1)      # flatten to (N,)
    W = np.asarray(connection_matrix, dtype=float)   # ensure float array

    # Validate dimensions
    if W.ndim != 2 or W.shape[0] != W.shape[1]:
        raise ValueError("connection_matrix must be square (N, N).")
    if W.shape[0] != p.shape[0]:
        raise ValueError("len(p0) must equal W.shape[0].")
    if np.any(W < 0):
        raise ValueError("connection_matrix must be non-negative.")
    if steps < 0:
        raise ValueError("steps must be a non-negative integer.")

    # Normalize rows to make matrix row-stochastic (sums = 1)
    row_sums = W.sum(axis=1, keepdims=True)
    if np.any(row_sums <= 0):
        raise ValueError("Each row must have a positive sum.")
    W = W / row_sums

    # Iterative propagation
    for _ in range(int(steps)):
        p = W @ p
        p = np.clip(p, 0.0, 1.0)  # ensure probabilities stay within [0, 1]

    return p


### Step 6 — Test the function with sample data


In [28]:
final_p = simulate_disease(p0, W, steps=10)
print("Final probabilities:", final_p)
print("Shape:", final_p.shape)
print("Min/Max:", final_p.min(), final_p.max())


Final probabilities: [0.42471743 0.42471749 0.42471745 0.42471718 0.42471733 0.42471748]
Shape: (6,)
Min/Max: 0.42471718485897547 0.42471749324274155


# Music Composition

Write a function named "compose_music" that takes a music sheet in A major scale as input and plays a piece of music based on the music sheet. The music sheet specifies a sequence of notes and their durations (see below for an example). You can use the in-class example "generate_sine" function to generate music notes with `fs = 8000`.

You can test your code using the example music_sheet below (simplified from "A Better Tomorrow (Mark's theme)" by Joseph Koo).
```py
music_sheet = [("Note_Cs", 0.5), ("Note_D", 0.5), ("Note_B", 0.5), ("Note_A_high", 1.5), ("Note_A_high", 0.5), ("Note_Gs", 0.5), ("Note_Fs", 0.5), ("Note_Gs", 0.5), ("Note_E", 0.75)]   
```
**Extra challenge**: Can you revise the function to play chords based on a given music sheet? A chord refers to the combination of two music nodes. (Extra challenge is not graded).

###  Step 1 — Define `generate_sine` function
This helper function creates a sine wave for a given frequency and duration.


In [32]:
import numpy as np
import sounddevice as sd   

def generate_sine(t_duration, f0, fs=8000):
    """
    Generate a sine wave of given frequency and duration.

    Parameters :

    t_duration : float
        Total duration of the note in seconds.
    f0 : float
        Frequency of the sine wave (Hz).
    fs : int
        Sampling rate in samples per second.

    Returns :

    np.ndarray
        1D NumPy array of the sine wave amplitudes.
    """
    # Create time samples
    t = np.linspace(0, t_duration, int(fs * t_duration), endpoint=False)
    # Generate the sine waveform
    y = np.sin(2 * np.pi * f0 * t)
    return y


### Step 2 — Define the note frequencies for A major scale
Start from base note A = 220 Hz and use equal-tempered scale intervals.


In [33]:
fs = 8000  # Sampling rate

# Define each note in the A major scale
Note_A       = generate_sine(0.5, 220, fs)
Note_B       = generate_sine(0.5, 220 * 2**(2/12), fs)
Note_Cs      = generate_sine(0.5, 220 * 2**(4/12), fs)
Note_D       = generate_sine(0.5, 220 * 2**(5/12), fs)
Note_E       = generate_sine(0.5, 220 * 2**(7/12), fs)
Note_Fs      = generate_sine(0.5, 220 * 2**(9/12), fs)
Note_Gs      = generate_sine(0.5, 220 * 2**(11/12), fs)
Note_A_high  = generate_sine(0.5, 440, fs)


### Step 3 — Prepare a music sheet
Each tuple represents (note_name, duration).  
We’ll later map each name to its waveform.


In [34]:
music_sheet = [
    ("Note_Cs", 0.5),
    ("Note_D", 0.5),
    ("Note_B", 0.5),
    ("Note_A_high", 1.5),
    ("Note_A_high", 0.5),
    ("Note_Gs", 0.5),
    ("Note_Fs", 0.5),
    ("Note_Gs", 0.5),
    ("Note_E", 0.75)
]


### Step 4 — Define the `compose_music` function
This function takes a music sheet and generates the full melody by concatenating notes.


In [35]:
def compose_music(music_sheet, fs=8000):
    """
    Compose a piece of music from a list of (note_name, duration) pairs.

    Parameters :

    music_sheet : list of tuples
        Each tuple contains (note_name: str, duration: float)
    fs : int
        Sampling rate for audio generation.

    Returns :

    np.ndarray
        1D NumPy array representing the full music waveform.
    """
    # Define the frequency mapping for the A major scale
    base_freq = 220
    note_freqs = {
        "Note_A": base_freq,
        "Note_B": base_freq * 2**(2/12),
        "Note_Cs": base_freq * 2**(4/12),
        "Note_D": base_freq * 2**(5/12),
        "Note_E": base_freq * 2**(7/12),
        "Note_Fs": base_freq * 2**(9/12),
        "Note_Gs": base_freq * 2**(11/12),
        "Note_A_high": 440
    }

    # Initialize an empty list to store generated notes
    music_waveform = []

    # Loop through the music sheet
    for note_name, duration in music_sheet:
        if note_name not in note_freqs:
            raise ValueError(f"Unknown note: {note_name}")
        frequency = note_freqs[note_name]

        # Generate sine wave for this note
        note_wave = generate_sine(duration, frequency, fs)

        # Append to the full music waveform
        music_waveform.append(note_wave)

    # Concatenate all note waveforms into one long signal
    music_waveform = np.concatenate(music_waveform)

    return music_waveform


### Step 5 — Generate and play the music
Use `compose_music()` to create the waveform and `sounddevice.play()` to listen.


In [36]:
# Generate the waveform
melody = compose_music(music_sheet, fs)

# Play the sound (comment out if sounddevice is unavailable)
sd.play(melody, fs)

# Wait until playback finishes
sd.wait()


# Rock Paper Scissor
Write a function named `play_rock_paper_scissor` so that a user can interact with the computer to play Rock Paper Scissor game. Here are the expected functionalities:
- For each round of the game, the function should ask the user whether the user wants to start playing by inputting 0 or 1. User input 0 indicates no, and 1 indicates yes.
- If the user wants to start the game, prompt the user to input a choice of action among Rock, Paper, Scissor. For now, you can safely assume the user's input is always among these three options. Randomly generate an action among Rock, Paper, Scissor for the computer. Please refer to our in-class practice problem for an example on random number generation.
- Compare the user input with the computer action, and print the winner based on the following rules:
    - Rock beats Scissors
    - Scissors beats Paper
    - Paper beats Rock
- Prompt the user whether the game should continue or not as we did in the first step.

### Step 1 — Define the game function
Define a function named `play_rock_paper_scissor()` that lets a user play the game against the computer.  
The game will keep running in a loop until the user chooses to stop.


In [37]:
import random

def play_rock_paper_scissor():
    """
    Let the user play Rock–Paper–Scissor with the computer.
    The game continues until the user decides to quit.
    """
    while True:
        # Ask if the user wants to start or continue
        start = int(input("Do you want to play? Enter 1 for Yes, 0 for No: "))
        if start == 0:
            print("Game ended. Thanks for playing!")
            break

        # Ask for the user’s choice
        user_choice = input("Choose Rock, Paper, or Scissor: ")

        # Randomly generate the computer’s choice
        computer_choice = random.choice(["Rock", "Paper", "Scissor"])
        print("Computer chose:", computer_choice)

        # Compare user and computer choices
        if user_choice == computer_choice:
            print("It's a tie!")
        elif (user_choice == "Rock" and computer_choice == "Scissor") or \
             (user_choice == "Scissor" and computer_choice == "Paper") or \
             (user_choice == "Paper" and computer_choice == "Rock"):
            print("You win!")
        else:
            print("Computer wins!")

        # Ask whether the user wants to play again
        continue_playing = int(input("Do you want to play again? Enter 1 for Yes, 0 for No: "))
        if continue_playing == 0:
            print("Goodbye!")
            break


### Step 2 — Run the function
Call the function to start the interactive game.


In [39]:
play_rock_paper_scissor()


Computer chose: Rock
It's a tie!
Computer chose: Rock
You win!
Computer chose: Scissor
It's a tie!
Goodbye!


# Linear Regression
- You are given a straight line learned from linear regression, denoted as $\hat{y}=ax+b$. Your task is to use a Python function named `eval_predict` to assess prediction quality over a dataset. Please first define the metric being used for assessment. Then let your program calculate and return the defined metric value.
- To learn a high-quality straight line in the form of $\hat{y}=ax+b$, we need to find optimal values for $a$
 and $b$. In what follows, you will perform grid search. You’ll try many pairs on a rectangular grid and pick the one with the best metric (defined in Problem 7) on the dataset. For example, consider a ∈ {0.0, 0.5, 1.0} and b ∈ {-1.0, 0.0, 1.0}, you evaluate all 9 combinations, compute the metric for each, and pick the best. Write a Python function named `grid_search` to find best pairs for given options of $a$ and $b$.

### Overview:
1. **Evaluate** how good a given line (with parameters `a` and `b`) is on a dataset.  
   → Implement `eval_predict(a, b, x, y)`
2. **Find the best parameters** `a` and `b` by testing all combinations from given lists.  
   → Implement `grid_search(a_list, b_list, x, y)`

### Step 1 — Define the evaluation metric
Use **Mean Squared Error (MSE)** as our metric:

\[
MSE = \frac{1}{n} \sum (y_i - \hat{y}_i)^2
\]

The smaller the MSE, the better the model.


In [1]:
import numpy as np

def eval_predict(a, b, x, y):
    """
    Evaluate prediction quality using Mean Squared Error (MSE).

    Parameters:

    a : float
        Slope of the line.
    b : float
        Intercept of the line.
    x : np.ndarray
        Input feature values.
    y : np.ndarray
        True target values.

    Returns:

    float
        Mean Squared Error between predicted and true values.
    """
    # Compute predictions
    y_hat = a * x + b

    # Compute MSE
    mse = np.mean((y - y_hat) ** 2)
    return mse


### Step 2 — Grid Search Concept
Perform a **grid search**:
- Loop through every combination of `a` and `b`
- Evaluate each using `eval_predict()`
- Keep track of the combination with the smallest MSE


In [2]:
def grid_search(a_list, b_list, x, y):
    """
    Perform grid search to find the best (a, b) pair that minimizes MSE.

    Parameters:

    a_list : list
        Candidate values for slope 'a'.
    b_list : list
        Candidate values for intercept 'b'.
    x : np.ndarray
        Input feature values.
    y : np.ndarray
        True target values.

    Returns:

    tuple
        (best_a, best_b, best_mse)
    """
    best_a, best_b = None, None
    best_mse = float('inf')  # initialize with infinity

    # Try every combination of (a, b)
    for a in a_list:
        for b in b_list:
            mse = eval_predict(a, b, x, y)
            if mse < best_mse:
                best_mse = mse
                best_a = a
                best_b = b

    return best_a, best_b, best_mse


### Step 3 — Test the functions
We’ll create a small synthetic dataset following approximately:
\[
y = 2x + 1
\]
and run our grid search to find the best parameters.


In [42]:
# Example dataset
x = np.array([0, 1, 2, 3, 4])
y = np.array([1, 3, 5, 7, 9])  # True model: y = 2x + 1

# Candidate parameter values
a_values = np.arange(0.0, 3.0, 0.5)
b_values = np.arange(-1.0, 2.0, 0.5)

# Run grid search
best_a, best_b, best_mse = grid_search(a_values, b_values, x, y)

print("Best a:", best_a)
print("Best b:", best_b)
print("Best MSE:", best_mse)


Best a: 2.0
Best b: 1.0
Best MSE: 0.0


# Sign-Up Validator
Imagine you are building a sign-up page for a new app. To keep the user database clean, you must validate all inputs before creating an account.
Instead of relying on advanced libraries, you’ll use pure Python basics.

### Username Validation
Write a function `validate_username(username)` that:
- Returns False if the username is empty, shorter than 3, or longer than 20 characters.
- Returns False if it contains anything besides letters, digits, underscore _, dot ., or hyphen -.
- Returns True if valid.

### Email Validation (Simple Version)
Write a function `validate_email(email)` that:
- Returns False if it doesn’t contain an "@".
- Splits the email into local part and domain (use .partition("@")).
- Ensures the domain contains at least one "." and doesn’t start/end with ".".
- Returns True if valid, False otherwise.

### Phone Normalization (Simplified)
Write a function `normalize_phone(phone, default_cc="+1")` that:
- Removes all non-digit characters.
- If the number doesn’t start with "+", prepend the default country code.
- Check that the final string has between 9 and 15 digits (excluding +).
- Return the normalized phone number (e.g., "+14155551212"), or "Invalid" if not valid.

### Sign-Up Aggregator
Write a function `validate_signup(user_info)` where `user_info` is a dictionary, e.g.:
```py
{
    "username": "alice_01",
    "email": "Alice@example.com",
    "password": "Strong!Pass1",
    "phone": "(415) 555-1212",
    "country": "us"
}
```
It should:
- Call each validation function.
- Collect any errors in a dictionary.
- Return a result like:
```py
{
    "ok": True,
    "errors": {},
    "normalized": {
        "username": "alice_01",
        "email": "alice@example.com",
        "phone": "+14155551212",
        "country": "US"
    }
}
```
If there are errors, `ok` should be False and errors should explain them.


### Step 1 — Username validation (`validate_username`)
Rules:
- Return `False` if empty, length < 3 or > 20.
- Return `False` if it contains anything besides letters, digits, underscore `_`, dot `.`, or hyphen `-`.
- Return `True` otherwise.


In [43]:
import re

def validate_username(username: str) -> bool:
    """
    Validate a username:
      - length in [3, 20]
      - only letters, digits, underscore, dot, hyphen
    """
    if username is None:
        return False
    username = username.strip()
    if not (3 <= len(username) <= 20):
        return False
    pattern = r'^[A-Za-z0-9_.-]+$'
    return re.fullmatch(pattern, username) is not None


### Step 2 — Email validation (simple) (`validate_email`)
Rules:
- Must contain "@"
- Use `partition("@")` to split into local and domain
- The domain must contain at least one "." and not start/end with "."
- Return `True` if valid, else `False`


In [44]:
def validate_email(email: str) -> bool:
    """
    Simple email validation per prompt:
      - contains '@'
      - use partition('@') to split into local and domain
      - domain contains at least one '.'
      - domain does not start or end with '.'
    """
    if email is None:
        return False
    local, sep, domain = email.partition("@")
    if sep == "":  # no '@'
        return False
    if not local or not domain:
        return False
    if "." not in domain:
        return False
    if domain.startswith(".") or domain.endswith("."):
        return False
    return True


### Step 3 — Phone normalization (simplified) (`normalize_phone`)
Rules:
- Remove all non-digit characters.
- If the original input does **not** start with "+", prepend `default_cc` (e.g., "+1").
- Check digit count (excluding '+') is between 9 and 15.
- Return normalized string like "+14155551212" or "Invalid".


In [45]:
def normalize_phone(phone: str, default_cc: str = "+1") -> str:
    """
    Normalize a phone number to a simplified E.164-like string.

    Steps:
      1) Detect whether the *original* string starts with '+'
      2) Remove all non-digit characters to get digits only
      3) If original did not start with '+', prepend default_cc
      4) Validate total digit count in [9, 15] (excluding '+')
      5) Return normalized '+<digits>' or 'Invalid'
    """
    if phone is None:
        return "Invalid"
    s = phone.strip()
    has_plus_prefix = s.startswith("+")
    digits = "".join(ch for ch in s if ch.isdigit())

    if not digits:
        return "Invalid"

    if has_plus_prefix:
        normalized = "+" + digits
    else:
        # Ensure default_cc looks like '+<ccdigits>'
        if not (default_cc and default_cc.startswith("+") and default_cc[1:].isdigit()):
            return "Invalid"
        normalized = default_cc + digits

    # Validate digit count (exclude '+')
    digit_count = len(normalized) - 1
    if 9 <= digit_count <= 15:
        return normalized
    return "Invalid"


### Step 4 — Sign-up aggregator (`validate_signup`)
- Call all validators
- Collect errors
- Produce a `normalized` object:
  - username: original if valid (or keep original even if invalid for visibility)
  - email: lowercased if valid
  - phone: normalized string or "Invalid"
  - country: uppercased if present
- Return:
```json
{
  "ok": true/false,
  "errors": {...},
  "normalized": {...}
}


In [46]:

def validate_signup(user_info: dict) -> dict:
    """
    Validate and normalize sign-up info.

    Expected keys in user_info:
      - username (str)
      - email (str)
      - password (str)  # not validated beyond presence in this prompt
      - phone (str)
      - country (str)
    """
    errors = {}
    normalized = {}

    # Username
    username = user_info.get("username", "")
    if not validate_username(username):
        errors["username"] = "Invalid username (length or characters)."
    normalized["username"] = username

    # Email
    email = user_info.get("email", "")
    if not validate_email(email):
        errors["email"] = "Invalid email format."
        normalized["email"] = email
    else:
        normalized["email"] = email.lower()

    # Phone
    phone = user_info.get("phone", "")
    # Use default_cc based on country if desired; here we stick with default "+1"
    normalized_phone = normalize_phone(phone, default_cc="+1")
    if normalized_phone == "Invalid":
        errors["phone"] = "Invalid phone number."
    normalized["phone"] = normalized_phone

    # Country
    country = user_info.get("country", "")
    normalized["country"] = country.upper() if isinstance(country, str) else country

    # Password (prompt does not specify rules; ensure presence only if you want)
    pwd = user_info.get("password", "")
    if pwd is None or pwd == "":
        errors["password"] = "Password is required."

    ok = (len(errors) == 0)
    return {"ok": ok, "errors": errors, "normalized": normalized}


### Step 5 — Tests
Try a valid case and several edge cases to verify behavior.


In [47]:
# Valid example from the prompt
user_ok = {
    "username": "alice_01",
    "email": "Alice@example.com",
    "password": "Strong!Pass1",
    "phone": "(415) 555-1212",
    "country": "us"
}
print(validate_signup(user_ok))

# Invalid username + invalid email + invalid phone
user_bad = {
    "username": "al!ce",          # invalid character '!'
    "email": "aliceexample.com",  # missing '@'
    "password": "123456",
    "phone": "12-34",             # too short
    "country": "uk"
}
print(validate_signup(user_bad))

# Already with international prefix
user_intl = {
    "username": "bob.k",
    "email": "bob.k@example.co.uk",
    "password": "ok",
    "phone": "+44 20 7946 0958",
    "country": "gb"
}
print(validate_signup(user_intl))


{'ok': True, 'errors': {}, 'normalized': {'username': 'alice_01', 'email': 'alice@example.com', 'phone': '+14155551212', 'country': 'US'}}
{'ok': False, 'errors': {'username': 'Invalid username (length or characters).', 'email': 'Invalid email format.', 'phone': 'Invalid phone number.'}, 'normalized': {'username': 'al!ce', 'email': 'aliceexample.com', 'phone': 'Invalid', 'country': 'UK'}}
{'ok': True, 'errors': {}, 'normalized': {'username': 'bob.k', 'email': 'bob.k@example.co.uk', 'phone': '+442079460958', 'country': 'GB'}}
